spring:
  datasource:
    url: jdbc:h2:mem:customers;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa.open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health